// source: https://gist.github.com/ksafranski/2973986

export const currencyList = [
	{
		symbol: "$",
		code: "USD",
		name: "US Dollar",
		decimal_digits: 2,
	},
	{
		symbol: "CA$",
		code: "CAD",
		name: "Canadian Dollar",
		decimal_digits: 2,
	},
	{
		symbol: "€",
		code: "EUR",
		name: "Euro",
		decimal_digits: 2,
	},
	{
		symbol: "AED",
		code: "AED",
		name: "United Arab Emirates Dirham",
		decimal_digits: 2,
	},
	{
		symbol: "Af",
		code: "AFN",
		name: "Afghan Afghani",
		decimal_digits: 0,
	},
	{
		symbol: "ALL",
		code: "ALL",
		name: "Albanian Lek",
		decimal_digits: 0,
	},
	{
		symbol: "AMD",
		code: "AMD",
		name: "Armenian Dram",
		decimal_digits: 0,
	},
	{
		symbol: "AR$",
		code: "ARS",
		name: "Argentine Peso",
		decimal_digits: 2,
	},
	{
		symbol: "AU$",
		code: "AUD",
		name: "Australian Dollar",
		decimal_digits: 2,
	},
	{
		symbol: "man.",
		code: "AZN",
		name: "Azerbaijani Manat",
		decimal_digits: 2,
	},
	{
		symbol: "KM",
		code: "BAM",
		name: "Bosnia-Herzegovina Convertible Mark",
		decimal_digits: 2,
	},
	{
		symbol: "Tk",
		code: "BDT",
		name: "Bangladeshi Taka",
		decimal_digits: 2,
	},
	{
		symbol: "BGN",
		code: "BGN",
		name: "Bulgarian Lev",
		decimal_digits: 2,
	},
	{
		symbol: "BD",
		code: "BHD",
		name: "Bahraini Dinar",
		decimal_digits: 3,
	},
	{
		symbol: "FBu",
		code: "BIF",
		name: "Burundian Franc",
		decimal_digits: 0,
	},
	{
		symbol: "BN$",
		code: "BND",
		name: "Brunei Dollar",
		decimal_digits: 2,
	},
	{
		symbol: "Bs",
		code: "BOB",
		name: "Bolivian Boliviano",
		decimal_digits: 2,
	},
	{
		symbol: "R$",
		code: "BRL",
		name: "Brazilian Real",
		decimal_digits: 2,
	},
	{
		symbol: "BWP",
		code: "BWP",
		name: "Botswanan Pula",
		decimal_digits: 2,
	},
	{
		symbol: "Br",
		code: "BYN",
		name: "Belarusian Ruble",
		decimal_digits: 2,
	},
	{
		symbol: "BZ$",
		code: "BZD",
		name: "Belize Dollar",
		decimal_digits: 2,
	},
	{
		symbol: "CDF",
		code: "CDF",
		name: "Congolese Franc",
		decimal_digits: 2,
	},
	{
		symbol: "CHF",
		code: "CHF",
		name: "Swiss Franc",
		decimal_digits: 2,
	},
	{
		symbol: "CL$",
		code: "CLP",
		name: "Chilean Peso",
		decimal_digits: 0,
	},
	{
		symbol: "CN¥",
		code: "CNY",
		name: "Chinese Yuan",
		decimal_digits: 2,
	},
	{
		symbol: "CO$",
		code: "COP",
		name: "Colombian Peso",
		decimal_digits: 0,
	},
	{
		symbol: "₡",
		code: "CRC",
		name: "Costa Rican Colón",
		decimal_digits: 0,
	},
	{
		symbol: "CV$",
		code: "CVE",
		name: "Cape Verdean Escudo",
		decimal_digits: 2,
	},
	{
		symbol: "Kč",
		code: "CZK",
		name: "Czech Republic Koruna",
		decimal_digits: 2,
	},
	{
		symbol: "Fdj",
		code: "DJF",
		name: "Djiboutian Franc",
		decimal_digits: 0,
	},
	{
		symbol: "Dkr",
		code: "DKK",
		name: "Danish Krone",
		decimal_digits: 2,
	},
	{
		symbol: "RD$",
		code: "DOP",
		name: "Dominican Peso",
		decimal_digits: 2,
	},
	{
		symbol: "DA",
		code: "DZD",
		name: "Algerian Dinar",
		decimal_digits: 2,
	},
	{
		symbol: "Ekr",
		code: "EEK",
		name: "Estonian Kroon",
		decimal_digits: 2,
	},
	{
		symbol: "EGP",
		code: "EGP",
		name: "Egyptian Pound",
		decimal_digits: 2,
	},
	{
		symbol: "Nfk",
		code: "ERN",
		name: "Eritrean Nakfa",
		decimal_digits: 2,
	},
	{
		symbol: "Br",
		code: "ETB",
		name: "Ethiopian Birr",
		decimal_digits: 2,
	},
	{
		symbol: "£",
		code: "GBP",
		name: "British Pound Sterling",
		decimal_digits: 2,
	},
	{
		symbol: "GEL",
		code: "GEL",
		name: "Georgian Lari",
		decimal_digits: 2,
	},
	{
		symbol: "GH₵",
		code: "GHS",
		name: "Ghanaian Cedi",
		decimal_digits: 2,
	},
	{
		symbol: "FG",
		code: "GNF",
		name: "Guinean Franc",
		decimal_digits: 0,
	},
	{
		symbol: "GTQ",
		code: "GTQ",
		name: "Guatemalan Quetzal",
		decimal_digits: 2,
	},
	{
		symbol: "HK$",
		code: "HKD",
		name: "Hong Kong Dollar",
		decimal_digits: 2,
	},
	{
		symbol: "HNL",
		code: "HNL",
		name: "Honduran Lempira",
		decimal_digits: 2,
	},
	{
		symbol: "kn",
		code: "HRK",
		name: "Croatian Kuna",
		decimal_digits: 2,
	},
	{
		symbol: "Ft",
		code: "HUF",
		name: "Hungarian Forint",
		decimal_digits: 0,
	},
	{
		symbol: "Rp",
		code: "IDR",
		name: "Indonesian Rupiah",
		decimal_digits: 0,
	},
	{
		symbol: "₪",
		code: "ILS",
		name: "Israeli New Sheqel",
		decimal_digits: 2,
	},
	{
		symbol: "₹",
		code: "INR",
		name: "Indian Rupee",
		decimal_digits: 2,
	},
	{
		symbol: "IQD",
		code: "IQD",
		name: "Iraqi Dinar",
		decimal_digits: 0,
	},
	{
		symbol: "IRR",
		code: "IRR",
		name: "Iranian Rial",
		decimal_digits: 0,
	},
	{
		symbol: "Ikr",
		code: "ISK",
		name: "Icelandic Króna",
		decimal_digits: 0,
	},
	{
		symbol: "J$",
		code: "JMD",
		name: "Jamaican Dollar",
		decimal_digits: 2,
	},
	{
		symbol: "JD",
		code: "JOD",
		name: "Jordanian Dinar",
		decimal_digits: 3,
	},
	{
		symbol: "¥",
		code: "JPY",
		name: "Japanese Yen",
		decimal_digits: 0,
	},
	{
		symbol: "Ksh",
		code: "KES",
		name: "Kenyan Shilling",
		decimal_digits: 2,
	},
	{
		symbol: "KHR",
		code: "KHR",
		name: "Cambodian Riel",
		decimal_digits: 2,
	},
	{
		symbol: "CF",
		code: "KMF",
		name: "Comorian Franc",
		decimal_digits: 0,
	},
	{
		symbol: "₩",
		code: "KRW",
		name: "South Korean Won",
		decimal_digits: 0,
	},
	{
		symbol: "KD",
		code: "KWD",
		name: "Kuwaiti Dinar",
		decimal_digits: 3,
	},
	{
		symbol: "KZT",
		code: "KZT",
		name: "Kazakhstani Tenge",
		decimal_digits: 2,
	},
	{
		symbol: "L.L.",
		code: "LBP",
		name: "Lebanese Pound",
		decimal_digits: 0,
	},
	{
		symbol: "SLRs",
		code: "LKR",
		name: "Sri Lankan Rupee",
		decimal_digits: 2,
	},
	{
		symbol: "Lt",
		code: "LTL",
		name: "Lithuanian Litas",
		decimal_digits: 2,
	},
	{
		symbol: "Ls",
		code: "LVL",
		name: "Latvian Lats",
		decimal_digits: 2,
	},
	{
		symbol: "LD",
		code: "LYD",
		name: "Libyan Dinar",
		decimal_digits: 3,
	},
	{
		symbol: "MAD",
		code: "MAD",
		name: "Moroccan Dirham",
		decimal_digits: 2,
	},
	{
		symbol: "MDL",
		code: "MDL",
		name: "Moldovan Leu",
		decimal_digits: 2,
	},
	{
		symbol: "MGA",
		code: "MGA",
		name: "Malagasy Ariary",
		decimal_digits: 0,
	},
	{
		symbol: "MKD",
		code: "MKD",
		name: "Macedonian Denar",
		decimal_digits: 2,
	},
	{
		symbol: "MMK",
		code: "MMK",
		name: "Myanma Kyat",
		decimal_digits: 0,
	},
	{
		symbol: "MOP$",
		code: "MOP",
		name: "Macanese Pataca",
		decimal_digits: 2,
	},
	{
		symbol: "MURs",
		code: "MUR",
		name: "Mauritian Rupee",
		decimal_digits: 0,
	},
	{
		symbol: "MX$",
		code: "MXN",
		name: "Mexican Peso",
		decimal_digits: 2,
	},
	{
		symbol: "RM",
		code: "MYR",
		name: "Malaysian Ringgit",
		decimal_digits: 2,
	},
	{
		symbol: "MTn",
		code: "MZN",
		name: "Mozambican Metical",
		decimal_digits: 2,
	},
	{
		symbol: "N$",
		code: "NAD",
		name: "Namibian Dollar",
		decimal_digits: 2,
	},
	{
		symbol: "₦",
		code: "NGN",
		name: "Nigerian Naira",
		decimal_digits: 2,
	},
	{
		symbol: "C$",
		code: "NIO",
		name: "Nicaraguan Córdoba",
		decimal_digits: 2,
	},
	{
		symbol: "Nkr",
		code: "NOK",
		name: "Norwegian Krone",
		decimal_digits: 2,
	},
	{
		symbol: "NPRs",
		code: "NPR",
		name: "Nepalese Rupee",
		decimal_digits: 2,
	},
	{
		symbol: "NZ$",
		code: "NZD",
		name: "New Zealand Dollar",
		decimal_digits: 2,
	},
	{
		symbol: "OMR",
		code: "OMR",
		name: "Omani Rial",
		decimal_digits: 3,
	},
	{
		symbol: "B/.",
		code: "PAB",
		name: "Panamanian Balboa",
		decimal_digits: 2,
	},
	{
		symbol: "S/.",
		code: "PEN",
		name: "Peruvian Nuevo Sol",
		decimal_digits: 2,
	},
	{
		symbol: "₱",
		code: "PHP",
		name: "Philippine Peso",
		decimal_digits: 2,
	},
	{
		symbol: "PKRs",
		code: "PKR",
		name: "Pakistani Rupee",
		decimal_digits: 0,
	},
	{
		symbol: "zł",
		code: "PLN",
		name: "Polish Zloty",
		decimal_digits: 2,
	},
	{
		symbol: "₲",
		code: "PYG",
		name: "Paraguayan Guarani",
		decimal_digits: 0,
	},
	{
		symbol: "QR",
		code: "QAR",
		name: "Qatari Rial",
		decimal_digits: 2,
	},
	{
		symbol: "RON",
		code: "RON",
		name: "Romanian Leu",
		decimal_digits: 2,
	},
	{
		symbol: "din.",
		code: "RSD",
		name: "Serbian Dinar",
		decimal_digits: 0,
	},
	{
		symbol: "RUB",
		code: "RUB",
		name: "Russian Ruble",
		decimal_digits: 2,
	},
	{
		symbol: "RWF",
		code: "RWF",
		name: "Rwandan Franc",
		decimal_digits: 0,
	},
	{
		symbol: "SR",
		code: "SAR",
		name: "Saudi Riyal",
		decimal_digits: 2,
	},
	{
		symbol: "SDG",
		code: "SDG",
		name: "Sudanese Pound",
		decimal_digits: 2,
	},
	{
		symbol: "Skr",
		code: "SEK",
		name: "Swedish Krona",
		decimal_digits: 2,
	},
	{
		symbol: "S$",
		code: "SGD",
		name: "Singapore Dollar",
		decimal_digits: 2,
	},
	{
		symbol: "Ssh",
		code: "SOS",
		name: "Somali Shilling",
		decimal_digits: 0,
	},
	{
		symbol: "SY£",
		code: "SYP",
		name: "Syrian Pound",
		decimal_digits: 0,
	},
	{
		symbol: "฿",
		code: "THB",
		name: "Thai Baht",
		decimal_digits: 2,
	},
	{
		symbol: "DT",
		code: "TND",
		name: "Tunisian Dinar",
		decimal_digits: 3,
	},
	{
		symbol: "T$",
		code: "TOP",
		name: "Tongan Paʻanga",
		decimal_digits: 2,
	},
	{
		symbol: "TL",
		code: "TRY",
		name: "Turkish Lira",
		decimal_digits: 2,
	},
	{
		symbol: "TT$",
		code: "TTD",
		name: "Trinidad and Tobago Dollar",
		decimal_digits: 2,
	},
	{
		symbol: "NT$",
		code: "TWD",
		name: "New Taiwan Dollar",
		decimal_digits: 2,
	},
	{
		symbol: "TSh",
		code: "TZS",
		name: "Tanzanian Shilling",
		decimal_digits: 0,
	},
	{
		symbol: "₴",
		code: "UAH",
		name: "Ukrainian Hryvnia",
		decimal_digits: 2,
	},
	{
		symbol: "USh",
		code: "UGX",
		name: "Ugandan Shilling",
		decimal_digits: 0,
	},
	{
		symbol: "$U",
		code: "UYU",
		name: "Uruguayan Peso",
		decimal_digits: 2,
	},
	{
		symbol: "UZS",
		code: "UZS",
		name: "Uzbekistan Som",
		decimal_digits: 0,
	},
	{
		symbol: "Bs.F.",
		code: "VEF",
		name: "Venezuelan Bolívar",
		decimal_digits: 2,
	},
	{
		symbol: "₫",
		code: "VND",
		name: "Vietnamese Dong",
		decimal_digits: 0,
	},
	{
		symbol: "FCFA",
		code: "XAF",
		name: "CFA Franc BEAC",
		decimal_digits: 0,
	},
	{
		symbol: "CFA",
		code: "XOF",
		name: "CFA Franc BCEAO",
		decimal_digits: 0,
	},
	{
		symbol: "YR",
		code: "YER",
		name: "Yemeni Rial",
		decimal_digits: 0,
	},
	{
		symbol: "R",
		code: "ZAR",
		name: "South African Rand",
		decimal_digits: 2,
	},
	{
		symbol: "ZK",
		code: "ZMK",
		name: "Zambian Kwacha",
		decimal_digits: 0,
	},
	{
		symbol: "ZWL$",
		code: "ZWL",
		name: "Zimbabwean Dollar",
		decimal_digits: 0,
	},
];

export const currencyCodeList = {
	USD: "US Dollar",
	CAD: "Canadian Dollar",
	EUR: "Euro",
	AED: "United Arab Emirates Dirham",
	AFN: "Afghan Afghani",
	ALL: "Albanian Lek",
	AMD: "Armenian Dram",
	ARS: "Argentine Peso",
	AUD: "Australian Dollar",
	AZN: "Azerbaijani Manat",
	BAM: "Bosnia-Herzegovina Convertible Mark",
	BDT: "Bangladeshi Taka",
	BGN: "Bulgarian Lev",
	BHD: "Bahraini Dinar",
	BIF: "Burundian Franc",
	BND: "Brunei Dollar",
	BOB: "Bolivian Boliviano",
	BRL: "Brazilian Real",
	BWP: "Botswanan Pula",
	BYN: "Belarusian Ruble",
	BZD: "Belize Dollar",
	CDF: "Congolese Franc",
	CHF: "Swiss Franc",
	CLP: "Chilean Peso",
	CNY: "Chinese Yuan",
	COP: "Colombian Peso",
	CRC: "Costa Rican Colón",
	CVE: "Cape Verdean Escudo",
	CZK: "Czech Republic Koruna",
	DJF: "Djiboutian Franc",
	DKK: "Danish Krone",
	DOP: "Dominican Peso",
	DZD: "Algerian Dinar",
	EEK: "Estonian Kroon",
	EGP: "Egyptian Pound",
	ERN: "Eritrean Nakfa",
	ETB: "Ethiopian Birr",
	GBP: "British Pound Sterling",
	GEL: "Georgian Lari",
	GHS: "Ghanaian Cedi",
	GNF: "Guinean Franc",
	GTQ: "Guatemalan Quetzal",
	HKD: "Hong Kong Dollar",
	HNL: "Honduran Lempira",
	HRK: "Croatian Kuna",
	HUF: "Hungarian Forint",
	IDR: "Indonesian Rupiah",
	ILS: "Israeli New Sheqel",
	INR: "Indian Rupee",
	IQD: "Iraqi Dinar",
	IRR: "Iranian Rial",
	ISK: "Icelandic Króna",
	JMD: "Jamaican Dollar",
	JOD: "Jordanian Dinar",
	JPY: "Japanese Yen",
	KES: "Kenyan Shilling",
	KHR: "Cambodian Riel",
	KMF: "Comorian Franc",
	KRW: "South Korean Won",
	KWD: "Kuwaiti Dinar",
	KZT: "Kazakhstani Tenge",
	LBP: "Lebanese Pound",
	LKR: "Sri Lankan Rupee",
	LTL: "Lithuanian Litas",
	LVL: "Latvian Lats",
	LYD: "Libyan Dinar",
	MAD: "Moroccan Dirham",
	MDL: "Moldovan Leu",
	MGA: "Malagasy Ariary",
	MKD: "Macedonian Denar",
	MMK: "Myanma Kyat",
	MOP: "Macanese Pataca",
	MUR: "Mauritian Rupee",
	MXN: "Mexican Peso",
	MYR: "Malaysian Ringgit",
	MZN: "Mozambican Metical",
	NAD: "Namibian Dollar",
	NGN: "Nigerian Naira",
	NIO: "Nicaraguan Córdoba",
	NOK: "Norwegian Krone",
	NPR: "Nepalese Rupee",
	NZD: "New Zealand Dollar",
	OMR: "Omani Rial",
	PAB: "Panamanian Balboa",
	PEN: "Peruvian Nuevo Sol",
	PHP: "Philippine Peso",
	PKR: "Pakistani Rupee",
	PLN: "Polish Zloty",
	PYG: "Paraguayan Guarani",
	QAR: "Qatari Rial",
	RON: "Romanian Leu",
	RSD: "Serbian Dinar",
	RUB: "Russian Ruble",
	RWF: "Rwandan Franc",
	SAR: "Saudi Riyal",
	SDG: "Sudanese Pound",
	SEK: "Swedish Krona",
	SGD: "Singapore Dollar",
	SOS: "Somali Shilling",
	SYP: "Syrian Pound",
	THB: "Thai Baht",
	TND: "Tunisian Dinar",
	TOP: "Tongan Paʻanga",
	TRY: "Turkish Lira",
	TTD: "Trinidad and Tobago Dollar",
	TWD: "New Taiwan Dollar",
	TZS: "Tanzanian Shilling",
	UAH: "Ukrainian Hryvnia",
	UGX: "Ugandan Shilling",
	UYU: "Uruguayan Peso",
	UZS: "Uzbekistan Som",
	VEF: "Venezuelan Bolívar",
	VND: "Vietnamese Dong",
	XAF: "CFA Franc BEAC",
	XOF: "CFA Franc BCEAO",
	YER: "Yemeni Rial",
	ZAR: "South African Rand",
	ZMK: "Zambian Kwacha",
	ZWL: "Zimbabwean Dollar",
};
